plugins {
    id 'net.neoforged.moddev' version '2.0.141'
}

repositories {
    maven {
        url = "https://maven.midnightdust.eu/releases"
    }
}

sourceSets {
    main {
        java.srcDir("../common/src/main/java")
        resources.srcDir("../common/src/main/resources")
    }
}

neoForge {
    version = rootProject.neoforge_version

    mods {
        smooth_f5 {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation jarJar("eu.midnightdust:midnightlib:1.9.3+26.1-neoforge")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}
